name = "SchurPolynomials"
uuid = "46c4bbdb-a633-4c08-a47d-0d4c54c9a6b2"
authors = ["Simeon David Schaub <schaub@mit.edu> and contributors"]
version = "0.1.0"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"

[compat]
AbstractAlgebra = "0.22"
DynamicPolynomials = "0.3, 0.4"
MutableArithmetics = "0.2"
Transducers = "0.4"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
